### ISSUE TITLE
JS: json files cause class cast exception

### ISSUE THREAD

**Issue by luca992** [icerockdev/moko-resources#327]
Loading a json file doesn't work because it causes a class cast exception.

For example this would fail: 
```
val JsonFile = FileResource(fileUrl = js("require(\"./files/JsonFile.json\")") as String)
```
because a required a json file returns a Json object, not a String

**Comment by Alex009** [comment]
@y9san9 check case please

**Comment by y9san9** [comment]
Actually, it seems to not fail if you are using generated moko-resources config, since the config declares `files` directory as assets, so json files will imported as assets, not as js object.

Last commit has added to the web demo such a case, which works fine. I think this issue is related to #326.

**Comment by luca992** [comment]
@y9san9 yeah, I think this is probably the same issue where the webpack isn't being applied correctly to the main module in a multi-module project. (where moko-resources is applied to a module that is a dependency of the main app module)
