### ISSUE TITLE
Unable to load string on iOS (Returns Key instead of Value)

### ISSUE THREAD

**Issue by TheArchitect123** [icerockdev/moko-resources#653]
Hi,

I'm currently trying to retrieve the string from Moko String Resource Dictionary on the Swift iOS side but I'm always getting back the string key instead of its value. 

**I have a kotlin service that Swift calls, which returns back a string.**
Here's how I get the string from the resource dictionary.

`Strings.getString(key);`

**I've also tried loading directly via Swift:**
`let string = MR.strings().my_string.desc().localized()`

Unable to load .strings file: CFBundle 0x2822c31e0 </var/containers/Bundle/Application/C3643B9A-6517-49BF-85D7-B33944F04B91/shared.app/KotlinMultiplatform:shared.bundle> (not loaded) / Localizable: Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character " at line 1" UserInfo={NSDebugDescription=Unexpected character " at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Missing ';' on line 409" UserInfo={NSDebugDescription=Missing ';' on line 409}}

@Alex009

**Comment by DavidRajPaul** [comment]
I too faced a similar issue. The problem was the string had "" in it. 

example: <string name="problematic_string">This was causing the issue \"%1$s\"?</string>

The string file when generated for iOS was not handling this and that is the reason "Missing ';' " was displayed in the error log.

Replacing  \"%1$s\" with \'%1$s\' fixed the issue for me.

Hope this helps :)

**Comment by Alex009** [comment]
generated Localizable.strings broken. check usage of " in your strings. replace to \"

**Comment by TheArchitect123** [comment]
Problem solved. Thanks.
It was a wrongly formatted escape character + some issues with copying the Resource File into the Swift bundle.
