### ISSUE TITLE
iOS Localized Strings using objC reserved keyword

### ISSUE THREAD

**Issue by cal-truli-ios** [icerockdev/moko-resources#763]
I have a list of countries that are keyed by their country code in my strings localization file:
![Screenshot 2024-09-06 at 9 42 17 AM](https://github.com/user-attachments/assets/2dbb0b66-4dfd-4f59-9a69-8e4859b7c230)

the resulting resource file in ObjC will not compile because the keyword 'NO' is reserved by the language:
![image](https://github.com/user-attachments/assets/e4802dd9-c7ad-4c66-b092-a8b20dbc79b3)

 Are there any solutions / alternatives to the way Moko creates the resource keys for iOS?

**Comment by Alex009** [comment]
i think this should be reported to Kotlin team in https://youtrack.jetbrains.com/newissue?project=kt because it's Kotlin/Native responsibility to mangle names that can conflict with ObjC.

while it not fixed i can suggest only to switch resources visibility level from public to internal - in this case MR will not be exposed to objc interface

**Comment by cal-truli-ios** [comment]
That solved my issue! thanks for the assistance :)
